# Questions 1:
Create a numpy array starting from 2 till 50 with a stepsize of 3.

In [5]:
import numpy as np

arr=np.array(np.arange(2,50,3))
print(arr)

[ 2  5  8 11 14 17 20 23 26 29 32 35 38 41 44 47]


# Questions 2:
Accept two lists of 5 elements each from the user.
Convert them to numpy arrays. Concatenate these arrays and print it. Also sort these arrays and print it. 

In [8]:
import numpy as np
arr1=np.array(list(input().split(" ")))
arr2=np.array(list(input().split(" ")))

print(arr1)
print(arr2)
arr = np.concatenate((arr1, arr2))
print(arr)
print(np.sort(arr))

4 3 7 8 9
1 23 45 21 6
['4' '3' '7' '8' '9']
['1' '23' '45' '21' '6']
['4' '3' '7' '8' '9' '1' '23' '45' '21' '6']
['1' '21' '23' '3' '4' '45' '6' '7' '8' '9']


# Questions 3:
Write a code snippet to find the dimensions of a ndarray and its size.

In [18]:
import numpy as np

arr = np.arange(30).reshape(6,5)
print(arr)
print()
print(arr.shape)
print(arr.size)


[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]
 [25 26 27 28 29]]

(6, 5)
30


# Questions 4:
How to convert a 1D array into a 2D array? Demonstrate with the help of a code snippet
Hint: np.newaxis, np.expand_dims

In [19]:
import numpy as np

a_1d = np.arange(12)
a_2d=a_1d.reshape(3,4)
print(a_1d)
print()
print(a_2d)

[ 0  1  2  3  4  5  6  7  8  9 10 11]

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


# Questions 5:
Consider two square numpy arrays. Stack them vertically and horizontally.
Hint: Use vstack(), hstack()

In [23]:
import numpy as np
arr1=np.arange(16).reshape(4,4)
arr2=np.arange(20,36).reshape(4,4)
print(arr1)
print()
print(arr2)
print()
print(np.hstack((arr1,arr2)))
print()
print(np.vstack((arr1,arr2)))

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]

[[20 21 22 23]
 [24 25 26 27]
 [28 29 30 31]
 [32 33 34 35]]

[[ 0  1  2  3 20 21 22 23]
 [ 4  5  6  7 24 25 26 27]
 [ 8  9 10 11 28 29 30 31]
 [12 13 14 15 32 33 34 35]]

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]
 [20 21 22 23]
 [24 25 26 27]
 [28 29 30 31]
 [32 33 34 35]]


# Questions 6:
How to get unique items and counts of unique items?

In [27]:
a= np.array([[1, 1], [2, 3],[4,4]])
unique, counts = np.unique(a, return_counts=True)
print(unique)
print(counts)



[1 2 3 4]
[2 1 1 2]
